version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./backend/.env
    volumes:
      - ./storage:/app/storage
    depends_on:
      - mongo
    networks:
      - gitviz-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - gitviz-network

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - gitviz-network

networks:
  gitviz-network:
    name: gitviz-network
    driver: bridge

volumes:
  mongo-data: