"""
Simple test server for the Documentation Generator.
This is a thin wrapper that uses GraphAwareDocGenerator for all functionality.

Usage:
    cd backend
    uv run python documentation_dev_server.py
    
Then open http://localhost:8080 in your browser.
"""

import sys
import os
from pathlib import Path

# Add paths for imports
sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent / "gitvizz"))

from http.server import HTTPServer, SimpleHTTPRequestHandler
import json
import threading

# Import the documentation generator
from documentation_generator import GraphAwareDocGenerator

# Store results globally for simplicity
generation_results = {
    "status": "idle",
    "topics": [],
    "files": {},
    "docs": {},
    "error": None,
    "graph_stats": {}
}


def generate_docs_for_path(repo_path: str, api_key: str = None, provider: str = "groq"):
    """Generate documentation using GraphAwareDocGenerator."""
    global generation_results
    
    try:
        generation_results["status"] = "Initializing..."
        generation_results["error"] = None
        
        def progress_callback(msg):
            generation_results["status"] = msg
            print(f"[DocGen] {msg}")
            sys.stdout.flush()
        
        # Create generator with the specified provider
        generator = GraphAwareDocGenerator(
            api_key=api_key,
            provider=provider,
            progress_callback=progress_callback
        )
        
        # Generate file-based documentation
        result = generator.generate_file_docs(
            repo_path=repo_path,
            max_files=20,
            files_per_page=8
        )
        
        if result["status"] == "success":
            # Convert docs to files format for UI - ONE ENTRY PER FILE
            docs = result.get("docs", {})
            generated_files = {}
            topics_data = []
            
            # Create individual page for each file
            for path, doc_info in docs.items():
                file_name = doc_info.get("name", "unknown")
                file_id = file_name.replace(".", "_").replace(" ", "_").lower()
                rel_path = doc_info.get("relative", "")
                role = doc_info.get("context", {}).get("role", "file")
                importance = doc_info.get("context", {}).get("importance", 0)
                
                # Create markdown content for this file
                content = doc_info.get("doc", f"# {file_name}\n\nNo documentation generated.")
                
                # Save as individual file
                generated_files[f"{file_id}.md"] = content
                
                # Add to sidebar as individual entry
                topics_data.append({
                    "id": file_id,
                    "title": file_name,
                    "description": f"{role.replace('_', ' ').title()} • {rel_path}",
                    "type": "file",
                    "role": role,
                    "importance": importance,
                    "path": rel_path
                })
            
            # Sort topics by importance (highest first)
            topics_data.sort(key=lambda x: x.get("importance", 0), reverse=True)
            
            # Create README
            stats = result.get("graph_stats", {})
            readme = f"""# Project Documentation

Generated by GitVizz Documentation Generator

## Statistics
- **Files Analyzed:** {result.get('total_files', 0)}
- **Files Documented:** {result.get('files_documented', 0)}
- **Code Nodes:** {stats.get('total_nodes', 0)}
- **Relationships:** {stats.get('total_edges', 0)}

## Documentation

"""
            for t in topics_data:
                readme += f"### [{t['title']}]({t['id']}.md)\n"
                readme += f"{t['description']}\n\n"
            
            generated_files["README.md"] = readme
            
            generation_results["topics"] = topics_data
            generation_results["files"] = generated_files
            generation_results["graph_stats"] = stats
            generation_results["status"] = "completed"
        else:
            generation_results["status"] = "error"
            generation_results["error"] = result.get("message", "Unknown error")
        
    except Exception as e:
        import traceback
        generation_results["status"] = "error"
        generation_results["error"] = f"{str(e)}\n\n{traceback.format_exc()}"


class DocGenHandler(SimpleHTTPRequestHandler):
    def log_message(self, format, *args):
        pass
        
    def do_GET(self):
        if self.path == "/":
            self.send_response(200)
            self.send_header("Content-type", "text/html")
            self.end_headers()
            self.wfile.write(HTML_PAGE.encode())
        elif self.path == "/api/status":
            self.send_response(200)
            self.send_header("Content-type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps(generation_results).encode())
        elif self.path.startswith("/api/file/"):
            filename = self.path[10:]
            if filename in generation_results["files"]:
                self.send_response(200)
                self.send_header("Content-type", "text/markdown")
                self.end_headers()
                self.wfile.write(generation_results["files"][filename].encode())
            else:
                self.send_response(404)
                self.end_headers()
    
    def do_POST(self):
        if self.path == "/api/generate":
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)
            data = json.loads(post_data.decode())
            
            repo_path = data.get("path", "")
            api_key = data.get("api_key", "")
            provider = data.get("provider", "groq")  # Default to groq
            
            if not repo_path or not os.path.exists(repo_path):
                self.send_response(400)
                self.send_header("Content-type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps({"error": f"Invalid path: {repo_path}"}).encode())
                return
            
            thread = threading.Thread(
                target=generate_docs_for_path, 
                args=(repo_path, api_key, provider)
            )
            thread.start()
            
            self.send_response(200)
            self.send_header("Content-type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"status": "started"}).encode())


HTML_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GitVizz Documentation Generator</title>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { 
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; 
            background: #fafafa; 
            color: #111; 
            line-height: 1.6;
        }
        .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
        
        /* Header */
        header { 
            background: #000; 
            color: #fff; 
            padding: 1.5rem 2rem;
            margin-bottom: 2rem;
        }
        header h1 { font-size: 1.5rem; font-weight: 600; }
        header p { color: #888; font-size: 0.875rem; margin-top: 0.25rem; }
        
        /* Form */
        .form-card {
            background: #fff;
            border: 1px solid #e5e5e5;
            border-radius: 8px;
            padding: 1.5rem;
            margin-bottom: 1.5rem;
        }
        .form-grid { display: grid; grid-template-columns: 1fr 1fr 150px 180px; gap: 1rem; align-items: end; }
        label { display: block; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: #666; margin-bottom: 0.5rem; }
        input, select { 
            width: 100%; 
            padding: 0.75rem 1rem; 
            border: 1px solid #ddd; 
            border-radius: 6px; 
            font-size: 0.875rem;
            font-family: inherit;
            background: #fff;
        }
        input:focus, select:focus { outline: none; border-color: #000; }
        button {
            background: #000;
            color: #fff;
            border: none;
            padding: 0.75rem 1.5rem;
            border-radius: 6px;
            font-size: 0.875rem;
            font-weight: 500;
            cursor: pointer;
            transition: background 0.2s;
        }
        button:hover { background: #333; }
        button:disabled { background: #ccc; cursor: not-allowed; }
        
        /* Status */
        .status-bar {
            background: #000;
            color: #fff;
            padding: 1rem 1.5rem;
            border-radius: 6px;
            margin-bottom: 1.5rem;
            display: none;
            align-items: center;
            gap: 1rem;
        }
        .status-bar.active { display: flex; }
        .spinner {
            width: 16px;
            height: 16px;
            border: 2px solid #333;
            border-top-color: #fff;
            border-radius: 50%;
            animation: spin 1s linear infinite;
        }
        @keyframes spin { to { transform: rotate(360deg); } }
        
        /* Stats */
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 1rem;
            margin-bottom: 1.5rem;
        }
        .stat-card {
            background: #fff;
            border: 1px solid #e5e5e5;
            border-radius: 8px;
            padding: 1.5rem;
            text-align: center;
        }
        .stat-value { font-size: 2rem; font-weight: 700; color: #000; }
        .stat-label { font-size: 0.75rem; color: #666; text-transform: uppercase; letter-spacing: 0.05em; margin-top: 0.25rem; }
        
        /* Main Layout */
        .main-grid { display: grid; grid-template-columns: 300px 1fr; gap: 1.5rem; }
        
        /* Sidebar */
        .sidebar {
            background: #fff;
            border: 1px solid #e5e5e5;
            border-radius: 8px;
            overflow: hidden;
        }
        .sidebar-header {
            background: #000;
            color: #fff;
            padding: 1rem;
            font-weight: 600;
            font-size: 0.875rem;
        }
        .file-list { max-height: 600px; overflow-y: auto; }
        .file-item {
            padding: 0.875rem 1rem;
            border-bottom: 1px solid #f0f0f0;
            cursor: pointer;
            transition: background 0.15s;
        }
        .file-item:hover { background: #f5f5f5; }
        .file-item.active { background: #000; color: #fff; }
        .file-item h3 { font-size: 0.875rem; font-weight: 500; }
        .file-item p { font-size: 0.75rem; color: #888; margin-top: 0.25rem; }
        .file-item.active p { color: #aaa; }
        
        /* Content */
        .content-area {
            background: #fff;
            border: 1px solid #e5e5e5;
            border-radius: 8px;
            padding: 2rem;
            min-height: 600px;
        }
        .content-area.empty {
            display: flex;
            align-items: center;
            justify-content: center;
            color: #888;
        }
        
        /* Prose */
        .prose h1 { font-size: 1.75rem; font-weight: 700; margin-bottom: 1.5rem; padding-bottom: 1rem; border-bottom: 2px solid #000; }
        .prose h2 { font-size: 1.25rem; font-weight: 600; margin-top: 2rem; margin-bottom: 1rem; color: #000; }
        .prose h3 { font-size: 1rem; font-weight: 600; margin-top: 1.5rem; margin-bottom: 0.5rem; }
        .prose p { margin-bottom: 1rem; color: #333; }
        .prose ul, .prose ol { padding-left: 1.5rem; margin-bottom: 1rem; }
        .prose li { margin-bottom: 0.5rem; color: #333; }
        .prose strong { font-weight: 600; color: #000; }
        .prose code { 
            font-family: 'JetBrains Mono', monospace;
            background: #f5f5f5;
            padding: 0.125rem 0.375rem;
            border-radius: 3px;
            font-size: 0.875em;
        }
        .prose pre { 
            background: #1a1a1a; 
            color: #f0f0f0;
            padding: 1.25rem; 
            border-radius: 8px; 
            overflow-x: auto;
            margin: 1rem 0;
            font-family: 'JetBrains Mono', monospace;
            font-size: 0.875rem;
            line-height: 1.5;
        }
        .prose pre code { background: none; padding: 0; color: inherit; }
        
        /* Mermaid */
        .mermaid-wrapper {
            background: #fafafa;
            border: 1px solid #e5e5e5;
            border-radius: 8px;
            padding: 1.5rem;
            margin: 1.5rem 0;
            overflow-x: auto;
        }
        .mermaid { text-align: center; }
    </style>
</head>
<body>
    <header>
        <h1>GitVizz Documentation Generator</h1>
        <p>Graph-aware documentation using AST analysis + LLM</p>
    </header>
    
    <div class="container">
        <div class="form-card">
            <div class="form-grid">
                <div>
                    <label>Repository Path</label>
                    <input type="text" id="repoPath" placeholder="C:\\path\\to\\repo">
                </div>
                <div>
                    <label>API Key</label>
                    <input type="password" id="apiKey" placeholder="Your API key...">
                </div>
                <div>
                    <label>Provider</label>
                    <select id="provider">
                        <option value="groq">Groq</option>
                        <option value="gemini">Gemini</option>
                        <option value="openai">OpenAI</option>
                    </select>
                </div>
                <div>
                    <button onclick="startGeneration()" id="genBtn">Generate Docs</button>
                </div>
            </div>
        </div>
        
        <div class="status-bar" id="status">
            <div class="spinner"></div>
            <span id="statusText">Initializing...</span>
        </div>
        
        <div class="stats-grid" id="stats" style="display: none;">
            <div class="stat-card">
                <div class="stat-value" id="statFiles">0</div>
                <div class="stat-label">Files Analyzed</div>
            </div>
            <div class="stat-card">
                <div class="stat-value" id="statNodes">0</div>
                <div class="stat-label">Code Nodes</div>
            </div>
            <div class="stat-card">
                <div class="stat-value" id="statEdges">0</div>
                <div class="stat-label">Relationships</div>
            </div>
        </div>
        
        <div class="main-grid" id="mainGrid" style="display: none;">
            <div class="sidebar">
                <div class="sidebar-header">Documentation Pages</div>
                <div class="file-list" id="fileList"></div>
            </div>
            <div class="content-area empty" id="content">
                <p>Select a file to view documentation</p>
            </div>
        </div>
    </div>
    
    <script>
        mermaid.initialize({ theme: 'neutral', startOnLoad: false });
        
        let polling = null;
        
        function startGeneration() {
            const path = document.getElementById('repoPath').value;
            const apiKey = document.getElementById('apiKey').value;
            const provider = document.getElementById('provider').value;
            
            fetch('/api/generate', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({ path, api_key: apiKey, provider })
            });
            
            document.getElementById('status').classList.add('active');
            document.getElementById('genBtn').disabled = true;
            
            polling = setInterval(checkStatus, 1000);
        }
        
        async function checkStatus() {
            const resp = await fetch('/api/status');
            const data = await resp.json();
            
            document.getElementById('statusText').textContent = data.status;
            
            if (data.graph_stats && data.graph_stats.total_nodes) {
                document.getElementById('stats').style.display = 'grid';
                document.getElementById('statFiles').textContent = data.graph_stats.files || Object.keys(data.graph_stats.node_categories || {}).length || 0;
                document.getElementById('statNodes').textContent = data.graph_stats.total_nodes || 0;
                document.getElementById('statEdges').textContent = data.graph_stats.total_edges || 0;
            }
            
            if (data.status === 'completed' || data.status === 'error') {
                clearInterval(polling);
                document.getElementById('genBtn').disabled = false;
                document.getElementById('status').classList.remove('active');
                
                if (data.status === 'error') {
                    alert('Error: ' + data.error);
                } else {
                    document.getElementById('mainGrid').style.display = 'grid';
                    renderFileList(data.topics);
                }
            }
        }
        
        function renderFileList(topics) {
            const container = document.getElementById('fileList');
            container.innerHTML = topics.map((t, i) => `
                <div class="file-item" data-file="${t.id}.md" onclick="viewFile('${t.id}.md', this)">
                    <h3>${t.title}</h3>
                    <p>${t.description}</p>
                </div>
            `).join('');
        }
        
        async function viewFile(filename, el) {
            // Update active state
            document.querySelectorAll('.file-item').forEach(item => item.classList.remove('active'));
            if (el) el.classList.add('active');
            
            const resp = await fetch('/api/file/' + filename);
            const content = await resp.text();
            
            const container = document.getElementById('content');
            container.classList.remove('empty');
            container.innerHTML = '<div class="prose">' + marked.parse(content) + '</div>';
            
            // Render mermaid diagrams
            container.querySelectorAll('pre code.language-mermaid').forEach((block, i) => {
                const wrapper = document.createElement('div');
                wrapper.className = 'mermaid-wrapper';
                const div = document.createElement('div');
                div.className = 'mermaid';
                div.textContent = block.textContent;
                wrapper.appendChild(div);
                block.parentNode.replaceWith(wrapper);
            });
            
            try {
                await mermaid.run();
            } catch(e) {
                console.log('Mermaid error:', e);
            }
        }
    </script>
</body>
</html>
"""

if __name__ == "__main__":
    port = 8080
    server = HTTPServer(("0.0.0.0", port), DocGenHandler)
    print(f"""
----------------------------------------------------------------
   GitVizz Documentation Generator - Dev Server
----------------------------------------------------------------
   URL: http://localhost:{port}
   Status: Ready
----------------------------------------------------------------
   This is a test server for development.
   In production, use the main server.py instead.
----------------------------------------------------------------
""")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nServer stopped.")
